name: Lacework Code Analysis (PR)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  LW_ACCOUNT_NAME: ${{ secrets.LACEWORK_CODE_SCANNING_ACCOUNT }}
  LW_API_KEY: ${{ secrets.LACEWORK_CODE_SCANNING_KEY_ID }}
  LW_API_SECRET: ${{ secrets.LACEWORK_CODE_SCANNING_SECRET }}

jobs:
  run-analysis:
    runs-on: ubuntu-20.04
    name: Run analysis
    strategy:
      matrix:
        target: [new, old]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Checkout old
        if: ${{ matrix.target == 'old' }}
        run: git checkout HEAD^1

      - name: Build
        run: |
          # build command

      - name: Analyze
        uses: lacework/code-security-action@v1
        with:
          target: ${{ matrix.target }}
          tools: sast
          classes: |
          # classes output or JAR file generated by the build

  display-results:
    runs-on: ubuntu-20.04
    name: Display results
    needs:
      - run-analysis
    steps:
      - name: Results
        id: code-analysis
        uses: lacework/code-security-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
